### ISSUE TITLE
"PowerShell Editor Services Host Process" orphans easily and chews up CPU when it is orphaned

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/PowerShellEditorServices#102]
This is specifically in the context of using the editor services with VS Code.

At one point, the process would occasionally spin to and stay at 100% CPU usage just while doing tab completion (and tab completion would become unresponsive), but I believe that was fixed at some point via an update to the extension. That issue was also easy to resolve because you could just restart Code and the process would be restarted with it.

In this specific case I just ran into, the processes remain after closing all instances of VS Code. You have to taskkill them all manually. It's hard to pinpoint when exactly these specific orphaned instances were created, but I believe it was related to several crashed debug sessions (that's for a separate bug report, but I have yet to find an easy, contained repro).

I don't necessarily have a specific resolution to this bug in mind, I just wish that when some sort of issue occurs with the editor services host and/or the debug client, it would use something less than 100% CPU and, even more ideally, would kill the process. It might be that the easiest solution here is to just fix the bugs that causes the host to become runaway.

![image](https://cloud.githubusercontent.com/assets/2292643/12083013/3304593a-b250-11e5-874e-8a2b7d29cd79.png)

**Comment by daviwil** [comment]
Yep, this is an issue with not handling the loss of the stdio streams after the parent process closes them.  I need to fix this generally but hadn't gotten back around to it yet.  Keith has already identified the source of the problem and filed a bug for it here:

https://github.com/PowerShell/PowerShellEditorServices/issues/31

I'll try to get that one fixed for the next release so that it goes away for good :)  I'll close your issue for now since the other one is already tracking it.

Thanks!

**Comment by daviwil** [comment]
By the way, your assumption about it being related to the debug adapter is correct.  When debugging, VS Code spins up a new instance of the host process for each launch.  These orphaned processes are likely due to a failure in the debugger that doesn't cause the process to crash but causes the VS Code debugger client to disconnect from it.  That would cause the process to be orphaned and then lose its stdio stream.
