### ISSUE TITLE
100% CPU When Expanding An Alias

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellEditorServices#104]
Co-worker is experiencing this. He also provided a crash dump but I don't see anything particularly useful. 

"To cause the problem, I found an alias in my script (highlighted because I had used ‘where’ instead of ‘where-object’) and picked the full cmdlet name from the dropdown."

![bug](https://cloud.githubusercontent.com/assets/1256531/12119328/b9701cc0-b390-11e5-8d0a-5f7a5eb5ca6f.jpg)

**Comment by daviwil** [comment]
There could be an infinite loop or something in the PowerShell code that the Expand Alias feature runs.

If he can repro it again, can you send me his EditorServices.log file from this path:

`c:\Users\username\.vscode\extensions\ms-vscode.PowerShell.[version]\bin`

E-mail is probably better than attaching here since the log details aren't scrubbed for personally identifiable information.  Sending a repro script that causes the problem would also be super helpful.

cc @dfinke

**Comment by dfinke** [comment]
I confused about the dropdown. Is this after doing and expand alias? That code doesn't present a dropdown.

**Comment by daviwil** [comment]
Hmmm, good point.  Maybe he means using IntelliSense on an alias?

**Comment by adamdriscoll** [comment]
I'll have him get a log.

**Comment by adamdriscoll** [comment]
It was a messed up install. Partial 0.3.1 install + a 0.2.0 install.

**Comment by daviwil** [comment]
Thanks for relaying the bug details!  Hopefully this won't be an issue for other users also...
