### ISSUE TITLE
Diagnostic logging no longer contains json output

### ISSUE THREAD

**Issue by corbob** [PowerShell/PowerShellEditorServices#1188]
I believe this is the result of the change to OmniSharp. In the preview extension, the EditorServices log no longer contains the json that is being passed around, just that a message is being passed. The legacy version however still contains the json.

Preview version:
![image](https://user-images.githubusercontent.com/30301021/74289317-9045c480-4ce3-11ea-9d12-04c1ad8a80ae.png)

Legacy version:
![image](https://user-images.githubusercontent.com/30301021/74289310-8d4ad400-4ce3-11ea-8e25-31728f5b9df1.png)

Was it intentional to remove these messages from the EditorServices log? Or was this inadvertent? When originally working out the code for Command Explorer, I made heavy use of the Diagnostic logging to ensure the messages were coming back as I expected them.

And the even bigger question: regardless of if the removal was intentional or not, are there plans to add such a level of logging back?

**Comment by rjmholt** [comment]
Yeah, [this is known](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#provide-language-server-protocol-payload-logs).

Basically VSCode has a logging solution, which is to send it log messages. Omnisharp does that and they show up in the Output window. We'd like to log the messages too, but that can't include the log messages, otherwise we'll be trying to send log messages logging the log messages, and log messages about those, and so on...

The solution in my mind lies with enabling a log sink in Omnisharp that can log all messages except log messages, but that's a change we need to happen in Omnisharp, since we don't control the message send/serialisation layer.

**Comment by corbob** [comment]
It would seem that turning on verbose trace logging is showing the json in the Output pane:
![image](https://user-images.githubusercontent.com/30301021/74378348-a6628c00-4d9a-11ea-80e8-99f3b7f5bc1d.png)

I'll leave it up to you if you want to keep the issue open. It would probably be helpful to have this logged to a file, but it sounds like that might be an Omnisharp thing to setup.

**Comment by andyleejordan** [comment]
Logging got revamped and supports the native LSP messages and VS Code's log output now.
