### ISSUE TITLE
Add language feature support for classes

### ISSUE THREAD

**Issue by kaylaerdmann** [PowerShell/PowerShellEditorServices#14]
The following features do not work when inside a class:
- Parameter hints
- Get Definition
- Get References
- Change Occurrences
- Symbol search

When outside of a class all features work normally.

**Comment by sgtoj** [comment]
Is there any update on this request?

**Comment by daviwil** [comment]
Hey Brian, not at the moment, but we'll definitely be adding it within the next few releases.  Which features have you been missing the most for classes so far?

**Comment by sgtoj** [comment]
Intelligent auto-completely and parameter hints are my number one.

**Comment by daviwil** [comment]
Can you give an example of what you mean by intelligent auto-completion?  Parameter hints for class methods are definitely coming!

**Comment by sgtoj** [comment]
Right now, the only completion feature VS Code has when working with classes is if it see I am typing a word that already exist, it will suggest it. What I mean is: only show me the methods and constructors for the respective class type. Furthermore, it would be nice if it understood the value-types I am currently typing and show the respective signature(s) as hints or show warnings when it the object doesn't have signature the for values being pass (assuming the value was explicitly typed).

**Comment by daviwil** [comment]
Yep, most of those things are definitely coming.

**Comment by Golosok** [comment]
Go to Definition on Method of Object would also be nice.

**Comment by daviwil** [comment]
@kapilmb, any chance you might be able to help with this one for 0.8.0 release (early October)?

**Comment by kapilmb** [comment]
@daviwil Sorry for getting back so late about this. Sure, you can assign this to me if you haven't started work on it already.

**Comment by daviwil** [comment]
Assigned, thanks Kapil!

**Comment by Golosok** [comment]
Any updates on this? Symbol search on class definitions/methods would be very nice.

**Comment by Golosok** [comment]
This issue is closed for a long time, but it doesn't really work. No symbols search, no go to definition, no itellisense for classes and methods on dot sourced files...
Any updates? Can provide screenshots of things that are not working if you need examples.

**Comment by Antasik** [comment]
Hi.
Any news about symbol search in classes? It has been "must have" feature since Powershell 5.0.

**Comment by livianaf** [comment]
Hello, 
I need this functionality too. Some years ago, I created an addon for PowerShell ISE to manage group of PS scripts in a similar way folders are used with VSCode (it is in [GitHub](https://github.com/livianaf/ProjectExplorer) too if some one need it). I added to it the "Get definition" and "Get references" functionalities covering classes too.

Now I 'm working with VSCode to manage different language files (including PS) under the same folder and the lack of those two functionalities is so annoying that I had to implement it. 

Probably it is not the best way to implement it but it works. I don't know if it is worth proposing a pull request for this change since this functionality will already be available in a next major version.

In any case, it is located in this [fork](https://github.com/livianaf/PowerShellEditorServices) if you want to review it.

**Comment by TylerLeonhardt** [comment]
@livianaf if you would like to send a PR that would be awesome :) this is highly requested and what better time to send a PR than [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Comment by livianaf** [comment]
Uf! I got too many errors I don't know how to manage :(

I'm sorry, this is my first PR. How can I get the detail of the errors generated by the PR checks?

**Comment by andschwa** [comment]
Fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1984
