### ISSUE TITLE
VSCode PowerShell Integrated Console hangs when running PSReadLine 2.2.0-beta3

### ISSUE THREAD

**Issue by alialo** [PowerShell/PowerShellEditorServices#1518]
VSCode PowerShell extension release [v2020.4.1-preview](https://github.com/PowerShell/vscode-powershell/releases/tag/v2020.4.1-preview) or newer causes the integrated console to hang when attempting to run code if [PSReadLine 2.2.0-beta3](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta3) is installed. The only changes introduced in v2020.4.1-preview are related to PowerShellEditorServices so I've raised the issue here and closed the existing one (can be found [here](https://github.com/PowerShell/vscode-powershell/issues/3441) for reference).

It appears to be related to [pull 1255](https://github.com/PowerShell/PowerShellEditorServices/pull/1255). Removing PSReadLine 2.2.0-beta3 and reverting back to beta2 fixes the problem, as does rolling back the extension to v2020.4.0-preview or older.

**Comment by andschwa** [comment]
Wow, thanks for the investigation! That's super interesting because we just recently traced an issue in PSReadLine 2.2.0-beta3 itself that caused more problems: https://github.com/PowerShell/PSReadLine/issues/2616 I'm wondering how this interaction played out.

**Comment by brwilkinson** [comment]
subscribe.

**Comment by andschwa** [comment]
So I think the way this played out is that in the rework in https://github.com/PowerShell/PowerShellEditorServices/pull/1255, PSES started using a linked cancellation token in PSReadLine to run correctly and asynchronously, but in beta3 of PSReadLine, the cancellation token was erroneously being dropped for an unlinked default token, which has now been fixed in https://github.com/PowerShell/PSReadLine/pull/2636.
