### ISSUE TITLE
[Revamp pipeline thread handling] Restore dialogue about PackageManagement installation

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1576]
From https://github.com/PowerShell/PowerShellEditorServices/pull/1459#discussion_r719637399.

The `ExecutePSCommandAsync()` API should allow us to both print errors to the console *and* throw them to the caller so they can take appropriate action.

Then we can use a `try`/`catch` at the callsite to handle the behaviour accordingly.

**Comment by andschwa** [comment]
@SydneyhSmith We need to decide if now is the time to remove all our workflows around package management, as it may not be the extension's place to deal with it.

**Comment by SydneyhSmith** [comment]
@andschwa I cant see anywhere PackageManagement is used by the extension so I am okay with not adding this back, and waiting for customer asks for it (reading back through old issues and PRs I am just seeing issues with it)...that being said I am totally open to the possibility that I am missing an important reason why this exists and would be happy to schedule time to add it back if that reason rises to the surface...

**Comment by SeeminglyScience** [comment]
Sorry I didn't see this. It's less to do with our workflows and more due to an old version of `PackageManagement` was causing dead locks due to some of the async stuff they were doing.

See #762

That old version may no longer cause the dead lock though, since we are no longer dependent on PowerShell's event system. Needs testing to be sure though.

**Comment by SydneyhSmith** [comment]
Thanks @SeeminglyScience that's super helpful

**Comment by SeeminglyScience** [comment]
Yeah I think we can strip all of this out now. Went into Windows PowerShell, reverted to stock PackageManagement and PowerShellGet, and intellisense no longer dead locks. Then if I go back to stable and I do `Find-Package -<tab>` it immediately dead locks.

This makes sense since we're no longer using the `OnIdle` event, so `PackageManagement` is now able to successfully marshal back to the pipeline thread. Side note, that does also mean PowerShell eventing *is* working in some respect.

**Comment by andschwa** [comment]
Heck yeah!
