### ISSUE TITLE
[Investigate] Fix PowerShell event handling

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShellEditorServices#1591]
From https://github.com/PowerShell/PSReadLine/pull/1679#issuecomment-947940473.

PowerShell events when run in a non-nested shell try to phone home back to the runspace in which they were registered, with the event handler calling in from another thread.

The assumption PowerShell makes is that [when an action occurs and we pulse the pipeline](https://github.com/PowerShell/PowerShell/blob/57f4ccd1fcbf15a2c143007102fb81a79decf3ea/src/System.Management.Automation/engine/EventManager.cs#L1026-L1058), [if the pipeline isn't nested, it must be on a different thread](https://github.com/PowerShell/PowerShell/blob/14f25c92e7616833639ceec6a729852fccfb31a4/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs#L205-L219).

Of course in our case, the pipeline is on our thread and isn't nested, because we're running it under an application. This seems to be an oversight in the PowerShell hosting model and I think it needs to be addressed in PowerShell; any attempt to run a PowerShell pipeline on a thread not dedicated to it will have this issue.

Unfortunately for us though, this is a behaviour we're stuck with in Windows PowerShell and PS 7.0, 7.1 and 7.2, so we have to work out what mitigation we can provide.

There are a couple of possible solutions:

1. We can construct an artificial internal cmdlet as our "top level" pipeline and put all of our actual execution underneath it. This would be relatively simple and would probably only have a bit of overhead, but would mean our pipelines are always nested, which could possibly have side-effects.
2. We could experiment with using reflection to just lie to PowerShell about our top-level pipeline being nested. This would probably hit errors somewhere, but might be worth a try.
3. The [`PSLocalEventManager`](https://github.com/PowerShell/PowerShell/blob/14f25c92e7616833639ceec6a729852fccfb31a4/src/System.Management.Automation/engine/EventManager.cs#L321) class is an internal extension of a public abstract class and most of its methods are virtual. We might conceivably be able to generate an override to this class and set it internally in the engine to redirect the eventing flow back to us. I'm not sure if this is possible, and if it is it would probably be a fair amount of work. But it would be the most "integrated" approach.
4. Abandon the event loop on the runspace thread and instead use it as a pump for a dedicated runspace thread. This would mean we can no longer run delegates on the runspace thread as we currently do (including at startup, when we implicitly run all our code on the runspace thread so that things like PSReadLine work correctly). We could address this by changing the delegate task implementation to use another internal cmdlet that simply executes the given delegate in its `EndProcessing()` block. But this would require some reimplementation inside the internal host.

It's also worth noting that, as far as we can tell, the ISE doesn't have any awareness of this scenario either. So it's not clear if this is a quiet bug in the ISE that either hasn't been noticed or hasn't been large enough to come to attention.

For now, I think, event handling in PSES isn't important enough to invalidate the work here and this is something I'm hopeful can be fixed later.

**Comment by andschwa** [comment]
Is there a way we could, like, turn off PowerShell events? Throw an error if one tries to be registered? Or would that involve having to do one of the four proposed workarounds?

**Comment by SeeminglyScience** [comment]
> For what it's worth I tried this in CreateInitialPowerShell

Yeah it's `Pipeline.IsNested`. Unfortunately that won't exist until runtime.

---

Did we switch back to using `ReuseThread` at some point? I thought we were using `CurrentThread` which would save the correct thread.

If we did, we could also take the PSRL approach and just invoke some quick meaningless powershell like `AddScript("0")` to force it. Pretty dirty, but it should work.

**Comment by andschwa** [comment]
@SydneyhSmith Marking this as a discussion since we're tracking the "bug" (mitigation fix) in https://github.com/PowerShell/vscode-powershell/issues/3701

**Comment by SeeminglyScience** [comment]
Does anyone remember what specifically they used to repro this? Seems to be working for me, it's possible I accidentally fixed this while getting attach to process working

**Comment by daxian-dbw** [comment]
I remember the repro is to register an event subscriber to the `Engine.Idle` event

**Comment by SeeminglyScience** [comment]
Then I think we're good 🎉 

![image](https://user-images.githubusercontent.com/24977523/167518266-a569ff5b-f6e6-4590-b2d0-3f90fdee5371.png)

**Comment by SeeminglyScience** [comment]
FWIW I think the issue was here:

https://cs.github.com/PowerShell/PowerShellEditorServices/blob/dd870ec1887c3cd69f18459d3e226067ab4f2098/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L940

That just creates a instance of PowerShell and assigns the runspace directly. What needed to happen was `PowerShell.Create(RunspaceMode.CurrentRunspace)` needed to be called instead to mark it as nested. That might have thrown at that point in initialization, but setting `Runspace.DefaultRunspace` would fix that I believe.

Part of the changes I made for attach to process is creating a new `PowerShell` instance for every context frame rather than reusing the old one. When I did that, since I was using `CurrentRunspace`, it's now marked as nested.

I'm gonna go ahead and close this

**Comment by daxian-dbw** [comment]
@SeeminglyScience As far as I can remember, it was because sometimes there was not running pipeline in the default session, and when an event was triggered in that case, the event manager created a pulse pipeline. However, while that pulse pipeline was running, something happens in the extension that causes a task to be queued and executed. Since they both use the same Runsapce at that point, the "a pipeline already running" exception will be thrown.
Is it now guaranteed that there is always a running pipeline within the default session of the integrated console?

**Comment by SeeminglyScience** [comment]
So I think what was happening was we create an instance of PowerShell that is not marked as `Nested`. Then in our OnIdle delegate, we were calling `PsesInternalHost.InvokePSCommand("0")` to trigger event handling.

But since we were doing that while the pipeline thread was technically busy, we *needed* the PowerShell instance to be marked `Nested` so it knows we're already on the right thread. So it knows *we're* the one making it busy. Since it wasn't marked `Nested`, it just threw every time we tried to trigger PowerShell event processing.

**Comment by andschwa** [comment]
I swear Rob and I both tried to get it marked Nested properly and ran into issues. IDK what you did, but you did good!

**Comment by daxian-dbw** [comment]
@SeeminglyScience Would be good to talk about how you did it (and maybe what was done wrong before) in the team meeting this week 😄
