### ISSUE TITLE
Paste into PSIC when using a Powershell Class appears to autocomplete early

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShellEditorServices#1684]
This may be PSReadline instead.

## Code
```ps
  [SiteDictionary]@([Site]@{
  'ID' = 'PE-STR'
  'Name' = 'Pester'
  'Description' = 'Pester'
  })
```

## Expected (PS7 Console)
![image](https://user-images.githubusercontent.com/15258962/151048721-53e32c4e-e713-4183-9337-ce8ab0396414.png)

## Actual (PSIC Console)
Paste by right-clicking into the PSIC console window

![image](https://user-images.githubusercontent.com/15258962/151048626-93ec1f42-1b89-43d6-969b-deaecd941312.png)
(Name and IPC are property names in the class)

## Notes
Does not happen when F8 is used

**Comment by SeeminglyScience** [comment]
Can you include minimal class definitions so it's easier to repro?

But it looks like it's getting <kbd>Tab</kbd> as input. That would make sense if the code you're pasting is using tabs for indentation, since right click just sends the text as if it were raw input. But the text here is definitely two spaces right?

**Comment by JustinGrote** [comment]
@SeeminglyScience oh good call! I checked this one file and for some reason it is set to save as tabs. Guess that's an argument against tabs eh?

**Comment by JustinGrote** [comment]
I'll close for now, there may be a realistic case for an enhancement to add an option to dynamically convert tabs to spaces when pasting PS code into the PSIC
