### ISSUE TITLE
$ label prefix interfering with completion list for $env:

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#206]
I can fix this issue by removing a "feature" I had added to present variables and parameters in the completion list with a prefix - namely `$` and `-`.  In ISE, it displays the text as returned by the AST with no prefix **but** ISE is able to use custom icons e.g.:

![ise_proplist](https://cloud.githubusercontent.com/assets/5177512/14340536/de993cea-fc45-11e5-9630-fd6854f0cb5e.png)
![ise_paramlist](https://cloud.githubusercontent.com/assets/5177512/14340537/e0bd06f0-fc45-11e5-98a0-f788c9b18a7f.png)

AFAIK we can't provide custom icons in VSCode so I changed the code to "prefix" variables and parameters so they would look a bit more "PowerShelly" e.g.:

![vscode_proplist](https://cloud.githubusercontent.com/assets/5177512/14340738/b9b707b6-fc47-11e5-8fbd-625d7693e65d.png)
![vscode_paramlist](https://cloud.githubusercontent.com/assets/5177512/14340740/bf4ae832-fc47-11e5-999c-77c6d64f69dd.png)

I can remove this special code which makes completion of `$env:` behave correctly but the completion lists look a little, well, naked IMO but functional is better than pretty.  :-)

![vscode_proplist2](https://cloud.githubusercontent.com/assets/5177512/14340753/e3454b24-fc47-11e5-83de-98d98e383209.png)
![vscode_paramlist2](https://cloud.githubusercontent.com/assets/5177512/14340755/e62cdcb2-fc47-11e5-83bd-a6e686ca7e3a.png)

**Comment by daviwil** [comment]
Yeah...  I like the addition of the `$` and `-`, so it'd be a shame to have to remove it.  I suppose there's not  a good way to determine whether the variable suggestion is coming after a variable namespace like `$env:` without looking at the source text.  I'd like to avoid that since it'd probably require some nasty code.

If there isn't an easy way to conditionally change the behavior in this case, let's just take it out.
