### ISSUE TITLE
Script file symbols should be sorted in alpha order - not in order of position in script

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#295]
When you're using this feature, scanning a list that isn't alpha sorted is a PITA.

**Comment by daviwil** [comment]
Hmmm...  I just tried sending back a sorted list from the language server.  Looks like VS Code is doing their own sorting based on file position so my ordering gets defeated.  And now that I search their issues list, looks like you already found this :smile:

https://github.com/Microsoft/vscode/issues/14240

Closing this issue since it's caused by VS Code.
