### ISSUE TITLE
Ship PowerShellEditorServices module to the PS Gallery

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShellEditorServices#310]
We should start shipping the PowerShell Editor Services module to the PowerShell Gallery so that other editors can easily pull down the dependency without having to bundle with their extension.

**Comment by tylerl0706** [comment]
Ah yes. This is still important.

**Comment by daviwil** [comment]
1.6 is a good time to start doing that I think.  It'd be useful for the Atom extension.

**Comment by jessebl** [comment]
Hi there. Is there anything that needs to be done to make this happen? I'd like to get my third-party editor working with this, without having to manually download and update this module.

**Comment by jessebl** [comment]
@SydneyhSmith I use Neovim. Partly switching to emacs right now too, but Neovim is my bread and butter.

**Comment by andschwa** [comment]
This is pretty low priority for us because it could potentially cause a lot of issues due the Editor Services' (and VS Code Extension's) current assumptions around the particular layout and bundled nature of all the required modules. It could also introduce more user confusion because many users (like those of the VS Code extension) _won't_ need to install Editor Services from the gallery, but seeing it available might try to anyway. I love both Emacs and NeoVim, and am going to attempt to add them to our CI matrix so I can assure continued support of these editors using their respective LSP clients to communicate with PSES, but for now downloading the released zip from the GitHub releases is probably going to remain the best solution. I'd honestly rather put work into automating that process for the popular Emacs and (Neo)Vim LSP clients than redo all the bundling and layout expectations just to get this on the gallery, which actually still wouldn't make the setup of these other clients _that much easier_.

**Comment by TylerLeonhardt** [comment]
@jessebl you should look at https://github.com/coc-extensions/coc-powershell

**Comment by andschwa** [comment]
Yup, and [lsp-mode](https://emacs-lsp.github.io/lsp-mode/) has one too (that's currently broken).

**Comment by jaccus** [comment]
How about when a user wants to invoke certain functionality of the module without having to install any UI editor? 

Scenario I am looking into is to ensure that, during a CI build, all PowerShell scripts are correctly auto-formatted using `ms-vscode.powershell` extension formatter. I do not want a CI pipeline to not rely on IDEs installed on build agents but do not see a way to do this without directly adding a direct dependency to PowerShellEditorServices module. Not having the module available via PSGallery makes it unnecessarily complicated to consume (e.g. requires manually republishing it somewhere else by the consumer).

**Comment by andyleejordan** [comment]
If you're looking for a formatter for CI you should be using PSScriptAnalyzer. The only thing the extension does is run that tool. Here's a GitHub Action to run it: https://github.com/microsoft/psscriptanalyzer-action

**Comment by jaccus** [comment]
Thanks for your reply. That was actually my initial expectation, however code formatted by psscriptanalyzer given identical PSScriptAnalyzerSettings.psd1 (`Invoke-Formatter -ScriptDefinition $fileContent -Settings ./PSScriptAnalyzerSettings.psd1`) gave me different result than just auto-formatting a ps1 file (where `"editor.defaultFormatter": "ms-vscode.powershell"`.

For example, psscriptanalyzer fixed certain psscriptanalyzer violations, but did not fix certain whitespace / newline issues that vscode extension does. But I guess this could be another layer of VSCode auto-formatting that applied its formatting on top of what `ms-vscode.powershell` did.
