### ISSUE TITLE
Include a .NET Client Class 

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShellEditorServices#42]
I'm finding it cumbersome to consume the message classes in PoshTools. It seems like there is a lot of plumbing that needs to go on to use them correctly. 

The [LanguageServiceManager](https://github.com/PowerShell/PowerShellEditorServices/blob/master/test/PowerShellEditorServices.Test.Host/LanguageServiceManager.cs) in the Host test project is a good example of how to host the process from .NET but it looks like there is a lot of work to do actually serialize the messages correctly and wait on them etc. I've been primarily looking at [ScenarioTest](https://github.com/PowerShell/PowerShellEditorServices/blob/master/test/PowerShellEditorServices.Test.Host/ScenarioTests.cs) for examples. 

I think it would be really neat to expose the same model found in the PowerShellEditorServices namespace through an abstracted namedspace in something like PowerShellEditorServices.Client. It would function similar to a WCF data context. We could then call methods like: 

```
 PowerShellClient.LanguageService.GetCompletionsInFile()
```

Rather than attempting to format the message classes correctly.

```
        await this.SendOpenFileEvent("TestFiles\\CompleteFunctionName.ps1");

        CompletionItem[] completions =
            await this.SendRequest(
                CompletionRequest.Type,
                new TextDocumentPosition
                {
                    Uri = "TestFiles\\CompleteFunctionName.ps1",
                    Position = new Position
                    {
                        Line = 5,
                        Character = 8
                    }
                });
```

I realize that the idea behind the non-.NET interface is so that any editor can interact with it but I figure that there are quite a few .NET editors out there that would benefit from this.

**Comment by daviwil** [comment]
I was getting started on a LanguageClient class a few days ago but didn't have time to get it to the level of quality it needed to be.  That's a high priority for me in the short term though because I definitely want to enable you to consume the host EXE using a simple interface.  

I like your point about being able to call similar methods to those that are in the core .NET API.  I've actually been thinking about putting the language/debugging feature implementations behind an interface so that they can be switched out for different versions of PowerShell.  This could also be useful for providing a facade over the LanguageClient so that the API can be used in the same way in the hosted process scenario.  How does that sound?

**Comment by adamdriscoll** [comment]
That sounds great! :+1:

**Comment by daviwil** [comment]
Working on a refactoring for this now.  My goal is to have NuGet packages out by the end of the week with a language/debugging service client that can be used easily from C# code.  Might even get to the bitness selection issue :)  I'll add you to the PR so you can take a look before I merge it.

**Comment by tylerl0706** [comment]
@adamdriscoll Do you still need this from PSES? There seems to be more official clients (especially for VS) for the language server protocol now.

**Comment by adamdriscoll** [comment]
No. I'd much rather just use the language server protocol stuff.
