### ISSUE TITLE
Debugger hangs when you press stop while an input prompt is active

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#428]
This is with PSES 0.12.1 and VSCode 1.11.0.  Try this.  Open a file and put in `Remove-Item`.  This will prompt you for a path to remove.  Stop debugging before replying to the prompt in the console.   The debugger appears to stop but if you try to debug again, it doesn't start debugging.

**Comment by daviwil** [comment]
Cool, I'll take a look tonight.  Aborting the execution should cancel the prompt, but maybe I lost that behavior with the integrated console changes

**Comment by daviwil** [comment]
Seems like there's a larger problem here where input prompts can't be cancelled via code, only through the integrated console.  I believe this was caused by my change to using Console.ReadKey synchronously on a background thread.  I think it's going to require a loop to check the state of the cancellation token while waiting for the string to be read on a different thread.  Not a huge change, but it'll require some testing.  Might have to hold off until the next update.

**Comment by daviwil** [comment]
Current work is here: https://github.com/daviwil/PowerShellEditorServices/commit/d3c440f0963951138e13e6f891734407b99644a0
