### ISSUE TITLE
Syntax colorization regex not properly handling parameter name -Function

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#49]
I think the regex is seeing only `Funtion` in `-Function` and gets thrown off.  Here is what I'm seeing:
![vscpowershellbadsyntaxcolorization](https://cloud.githubusercontent.com/assets/5177512/11310122/00c9c420-8f85-11e5-8963-317bad4a8ecb.png)

**Comment by daviwil** [comment]
Looks like the regex that identifies the keyword 'function' is superceding the parameter regex.  Maybe @Jaykul knows why this may be happening?  He has some familiarity with TextMate bundle we're using.

**Comment by Jaykul** [comment]
That bug exists in sublime too.

**Comment by Jaykul** [comment]
This is extra fun, because github uses our lexer, so you can demo these bugs inline :-)

```posh
# This is ok
Test-Highlight -Something StringValue
# This is not
Test-Highlight -TestFunction StringValue
# and it breaks this:
Test-Highlight -Something StringValue
```

Scope on function was also broken, like:

```posh
function Test-Thing { Get-Command $global:VariableName }
function global:Test-Thing { Get-Command $global:VariableName }
Function LOCAL:Test-Thing { Get-Command $global:VariableName }
FUNCTION script:Test-Thing { Get-Command $global:VariableName }
```

So I fixed it all 
https://github.com/SublimeText/PowerShell/pull/137

**Comment by rkeithhill** [comment]
Yup, that fixes it for VSCode as well. @daviwil - do you want me to submit a PR for this? I was just going to copy the contents of PowershellSyntax.tmLanguage from the Sublime repo (what Joel just checked in) into the PowerShell.tmlanguage file.  Or is there other massaging that goes on for that file?

**Comment by daviwil** [comment]
I'll have to submit a PR to the vscode repo since I apparently should not have been including the syntax definition file in my extension anyway :)  I'll do that now.

**Comment by daviwil** [comment]
And forgot to say, thanks @Jaykul for fixing that!

**Comment by daviwil** [comment]
Actually @Jaykul, since the change is fairly small, do you want to do the PR to VS Code to get credit for the fix?  Easier that way since there's no question about the licensing of the fix ;)

The TextMate bundle file is located here:

https://github.com/Microsoft/vscode/blob/master/extensions/powershell/syntaxes/PowershellSyntax.tmLanguage

It's the same file as Sublime Text's bundle so you can just copy/paste your new file contents into that.

**Comment by Jaykul** [comment]
I'd love to.

**Comment by vors** [comment]
This one is fun, it was already fixed once the same way by @bcrotty and according to my comment it made had some horrible side-effect.

https://github.com/SublimeText/PowerShell/issues/80


I digged this thread after merging Jaykul's PR. I think it's fine, since it was done in `dev` branch.
@daviwil I think Sublime bundle need a new release, which we should push to all sources.

**Comment by daviwil** [comment]
Jaykul has already got a PR merged into VS Code to fix the bundle there.  Will this change break everything?  Should we get them to revert the commit?

**Comment by Jaykul** [comment]
'course it doesn't "break everything" whatchu take me for? ;-)

@bcrotty's change was really different (and included a *lot* of other things).

**Comment by daviwil** [comment]
I will never again doubt The @Jaykul ;)

**Comment by rkeithhill** [comment]
This issue is external to the editor services.  Closing it.
