### ISSUE TITLE
"configuration" breaking Syntax Highlighting

### ISSUE THREAD

**Issue by bcrotty** [PowerShell/PowerShellEditorServices#52]
![2015-11-23 12_56_30-photos](https://cloud.githubusercontent.com/assets/6155964/11346338/c8233dcc-91e1-11e5-96e5-ae8403c9d4ca.png)

The word "configuration" appears to break syntax highlighting.

**Comment by bcrotty** [comment]
![2015-11-23 12_59_17-c__users_bcrotty_onedrive_script archive_select franchise network discovery ps1](https://cloud.githubusercontent.com/assets/6155964/11346390/0a8bfb86-91e2-11e5-9984-91b5d5e01b09.png)

When I take out "configuration", this is what it looks like.

**Comment by vors** [comment]
Hi @bcrotty 
Good to see you here :)

PowerShellEditorServices doesn't provide their own syntax highlighting ( @daviwil correct me, if I'm wrong).
Syntax definition for VSCode leaves in https://github.com/SublimeText/PowerShell
So this bug should be probably linked to some bug there.

**Comment by daviwil** [comment]
Yep, that's correct.  In fact, the syntax highlighting for PowerShell in VS Code is a part of VS Code itself:

https://github.com/Microsoft/vscode/blob/master/extensions/powershell/syntaxes/PowershellSyntax.tmLanguage

However, filing these bugs against vscode-powershell makes sense so that they're tracked in a less noisy place.  Also filing them (and fixing them) against the Sublime text repo can't hurt.

**Comment by bcrotty** [comment]
Thanks! Sorry I haven't been able to contribute recently. I'll post this there as well.

**Comment by Jaykul** [comment]
I'm not sure if the Sublime repo can serve as the official repository for stuff like this.

Sublime has decided they need a more stateful and *testable* syntax (LL parser) for this stuff, so they're about to move off .tmLanguage https://github.com/SublimeText/PowerShell/pull/127

**Comment by daviwil** [comment]
This issue is now tracked in the SublimeText/PowerShell repo: https://github.com/SublimeText/PowerShell/issues/140
