### ISSUE TITLE
Implement code reformatting feature

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShellEditorServices#54]
This would negate the following Issue in PSScriptAnalyzer https://github.com/PowerShell/PSScriptAnalyzer/issues/379

**Comment by kilasuit** [comment]
100 is just a suggestion btw

**Comment by daviwil** [comment]
This is something that should be implemented in the individual editors rather than in the core Editor Services platform.  Most editors have some level of word wrapping functionality built in so that should be sufficient to automatically break lines after some length.

However, a code reformatting action is something that is on my radar.  This would be invoked by the editor but fulfilled by Editor Services so that the code gets reformatted based on generally accepted formatting rules.  I think adding line breaks makes sense here, so I'll rename the issue to reflect the feature in this context.

Thanks Ryan!

**Comment by bryanwinstead** [comment]
Any reformatter needs to be highly customizable, otherwise it's basically useless. Unfortunately, PowerShell does not have the luxury of a universally accepted or enforced style guide.

That being said, it is something that would be very helpful to have, if implemented properly.

**Comment by daviwil** [comment]
We're discussing this over at https://github.com/PowerShell/vscode-powershell/issues/167 right now, planning to start implementing it fairly soon!

**Comment by daviwil** [comment]
We'll have a first pass implementation of a new code formatter in this week's release!
