### ISSUE TITLE
System.InvalidOperation exception from PSSA

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellEditorServices#572]
I've been debugging other issues in PSES and I'm seeing multiple instances of this exception.  Can this be safely ignored or is there a problem here:

![image](https://user-images.githubusercontent.com/5177512/32411787-c49c3452-c1a9-11e7-8144-33ff50f27ce1.png)

![image](https://user-images.githubusercontent.com/5177512/32411788-c9165828-c1a9-11e7-99e8-8ffee656f8dc.png)

**Comment by tylerl0706** [comment]
@kapilmb doesn't work on the team anymore so I don't think he'll have cycles to look at this. Do you think you could give me a little bit more background?

**Comment by rkeithhill** [comment]
I probably should have submitted this to the PSSA project since it is a bug in the PSSA dll.

**Comment by tylerl0706** [comment]
@rkeithhill no worries! Any idea if it's still happening?

**Comment by rkeithhill** [comment]
I think so but you have to configure the debugger to break when IOPEx is first thrown IIRC.

**Comment by bergmeister** [comment]
@rkeithhill @tylerl0706 This has been reported in PSSA as well here: https://github.com/PowerShell/PSScriptAnalyzer/issues/902 and the results currently are:
- It only happens on slow-ish machines like e.g. a `Standard D2s v3 (2 vcpus, 8 GB memory)` VM in Azure (it did not repro on my physical dev machine)
- The exception happens when calling `Invoke()` on the `PowerShell` class created by `PowerShell.Create()`. The created PowerShell class is being correctly disposed afterwards and the comment on it says that it is thread safe. PSSA is spawning a thread for each rule and therefore this seems to be a bug in PowerShell itself: https://github.com/PowerShell/PowerShell/issues/6422
- This applies to Windows PowerShell and PowerShell Core

**Comment by rkeithhill** [comment]
Copied over to PSSA - https://github.com/PowerShell/PSScriptAnalyzer/issues/959
