### ISSUE TITLE
We need a way to customize output color for error/warning, etc

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShellEditorServices#651]
Specifically, in PowerShell.exe we have the ability to change the color used for errors, warnings, etc.: 

```
C:\PS> $Host.PrivateData                                                    
                                      
ErrorForegroundColor    : DarkRed     
ErrorBackgroundColor    : Black       
WarningForegroundColor  : Yellow      
WarningBackgroundColor  : Black       
DebugForegroundColor    : Green       
DebugBackgroundColor    : Black       
VerboseForegroundColor  : Cyan        
VerboseBackgroundColor  : Black       
ProgressForegroundColor : DarkMagenta 
ProgressBackgroundColor : Gray        
```

In VSCode I can change the colors of the 16 ANSI colors, but I can't find a way to change which of them you are using to write errors out.

**Comment by tylerl0706** [comment]
Thanks Joel! I reasonable request indeed.

**Comment by SeeminglyScience** [comment]
If anyone is interested in picking this up the general idea is to

1. Port [ConsoleColorProxy](https://github.com/PowerShell/PowerShell/blob/25dbc68b8e50b9b6706cec2a7fe3bccfe7736e04/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L737) and the [PrivateData member](https://github.com/PowerShell/PowerShell/blob/25dbc68b8e50b9b6706cec2a7fe3bccfe7736e04/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L852) from `ConsoleHost` in pwsh to [EditorServicesPSHost.PrivateData](https://github.com/PowerShell/PowerShellEditorServices/issues/651)

1. Change the [Write* methods in EditorServicesPSHostUserInterface](https://github.com/PowerShell/PowerShellEditorServices/blob/a0761cf8cce885ec70c9307fa600aa02f2f4b441/src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs#L526) to use the new colors

**Comment by KeroroLulu** [comment]
I would like to work on it !

**Comment by tylerl0706** [comment]
@KeroroLulu you can work on any issue at any time you'd like :)

We don't usually 'assign' work. You can freely start and submit a Pull Request when you're ready to get feedback!

**Comment by KeroroLulu** [comment]
@tylerl0706  Thank you :)

I'm not used to stuff like that, so if I have any questions I'll ask you !

**Comment by tylerl0706** [comment]
You can always ask questions too!

Let me know if you have any 👍

**Comment by KeroroLulu** [comment]
@tylerl0706 In the instructions 

> Port ConsoleColorProxy and the PrivateData member from ConsoleHost in pwsh to EditorServicesPSHost.PrivateData

The link for EditorServicesPSHost.PrivateData redirect here, I should create this file and copy/past ConsoleColorProxy class and PrivateData member in it, or this file already exist ?

**Comment by tylerl0706** [comment]
No problem :) Port usually means "take that and add it to this" sometimes it does mean actually copy/paste. However I think it's a little bit more work than copy/paste.

First copy paste those classes over into `EditorServicesPSHost.PrivateData`, then try to build and see what you need to fix to get those classes to work in `PSES`(PowerShell Editor Services).

Then, follow @SeeminglyScience's next step and Change the Write* methods in EditorServicesPSHostUserInterface to use the new colors.

**Comment by KeroroLulu** [comment]
@tylerl0706 Ok ! But I have to copy ConsoleColorProxy class into the override or above like in ConsoleHost ?

**Comment by tylerl0706** [comment]
What was the error that you got?

**Comment by KeroroLulu** [comment]
@tylerl0706 My powershell is in french but by translating we got : 

`Session/Host/EditorServicesPSHost.cs(89,38): error CS0122: 'ConsoleHostUserInterface' 
is unreachable because of its level of protection`

I think that's because ConsoleHostUserInterface is in Powershell and not in Powershell Editor Service

**Comment by tylerl0706** [comment]
Ah yeah you should replace that with `EditorServicesPSHostUserInterface` probably

**Comment by KeroroLulu** [comment]
@tylerl0706 The problem is that `EditorServicesPSHostUserInterface` doesn't contain any color method so when I replace `ConsoleHostUserInterface` I have this error : 

`Session/Host/EditorServicesPSHost.cs(99,45): error CS1061: 'EditorServicesPSHostUserInterface' doesn't contain any definition for 'ErrorForegroundColor' and there's no extension's method 'ErrorForegroundColor' accepting first argument of type 'EditorServicesPSHostUserInterface' has been found`

Should I implement all method for background and foreground color in **EditorServicesPSHost** ? Or should I just copy/past **ConsoleHostUserInterface** file from pwsh to pwsh editor services ?

(Sorry for asking so many questions ^^")

**Comment by tylerl0706** [comment]
You should be able to add these that I see in ConsoleHostUserInterface:
https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1359-L1376

to `EditorServicesPSHostUserInterface`

**Comment by tylerl0706** [comment]
And then don't forget to edit these to use those values instead of the hardcoded ones 🙂 
https://github.com/PowerShell/PowerShellEditorServices/blob/a0761cf8cce885ec70c9307fa600aa02f2f4b441/src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs#L526

Ask all the questions you need. You've got this 💪 you're going to fix this issue 😃

**Comment by tylerl0706** [comment]
That's great @KeroroLulu!

Here's what you can do to test:
Right now, the best way to do this is by building and launching the vscode powershell extension.

Follow these instructions to test your code out:
https://github.com/PowerShell/vscode-powershell/blob/master/docs/development.md

**Comment by KeroroLulu** [comment]
@tylerl0706 Should I add Unit Test to my code ?

**Comment by KeroroLulu** [comment]
@tylerl0706 Should I add Unit Test to my code ?

Edit

I'm on mac and I'm trying to launch the extension with F5, it propose me several process to attach my extension (zsh, adobe, cloud, etc...) which one should I use ?

Edit 2

I did it somehow by using code-insiders --extensionDevelopmentPath="/Users/My/vscode-powershell" but then I don't know how it works exactly I tried to change some background value for warning but it change nothing so I don't know if this is the code or the way I test it.

**Comment by tylerl0706** [comment]
@KeroroLulu does `$Host.PrivateData` give you anything?

**Comment by KeroroLulu** [comment]
It gives me : 
```
ErrorForegroundColor    : Red
ErrorBackgroundColor    : -1
WarningForegroundColor  : Yellow
WarningBackgroundColor  : -1
DebugForegroundColor    : Yellow
DebugBackgroundColor    : -1
VerboseForegroundColor  : Yellow
VerboseBackgroundColor  : -1
ProgressForegroundColor : Yellow
ProgressBackgroundColor : DarkCyan
```
I just tested it by deleting the message but it's just my way to test it that doesn't work. How can I print warning or error by using PWSH Editor Services ?

**Comment by tylerl0706** [comment]
If you change `$Host.PrivateData.ErrorForegroundColor` in the integrated terminal to DarkCyan, and do a:

`Write-Error "foo"`

does it still print in red or dark cyan?

Note this will only work if you made the correct changes to the `Write*` function here:
https://github.com/PowerShell/PowerShellEditorServices/blob/a0761cf8cce885ec70c9307fa600aa02f2f4b441/src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs#L565

to use the `this.ErrorForegroundColor` (I think it's called) instead of "Red"

**Comment by tylerl0706** [comment]
That's great @KeroroLulu!! 🎉 🎉
