### ISSUE TITLE
Terminal Scrolling

### ISSUE THREAD

**Issue by GHRoss** [PowerShell/PowerShellEditorServices#683]
PSReadLine 2.0.0
macOS High Sierra 10.13.4
PowerShell v6.1.0-preview.2
VS Code 1.24.0
PowerShell extension: 1.7.0-insiders-557

I'm unable to scroll up in the terminal without the terminal forcing itself back to the bottom.

**Comment by rjmholt** [comment]
Hi @GHRoss, is this just in the Integrated Console or also in VSCode's console (running bash or PowerShell)?

**Comment by GilmondRoss** [comment]
Hi @rjmholt,

This is in the VS Code integrated console running PSReadLine 2.0.0.

I couldn't recreate the issue with Windows 10, however.

**Comment by rjmholt** [comment]
Ah that's helpful to know! Thanks!

**Comment by GHRoss** [comment]
Hi @rjmholt,

This is in the VS Code integrated console running PSReadLine 2.0.0.

I couldn't recreate the issue with Windows 10, however.

**Comment by rjmholt** [comment]
This is also occurring on Ubuntu18.04

**Comment by GHRoss** [comment]
Just tried PSReadLine 2.0.0 in the macOS terminal (outside the VSCode integrated terminal) and got the same thing.

**Comment by tylerl0706** [comment]
@SeeminglyScience this is a V2 issue :)

**Comment by GHRoss** [comment]
@SeeminglyScience Let me know if you need me to test this.

**Comment by SeeminglyScience** [comment]
When a cursor position API is called on Unix-like platforms the report cursor position query is emitted to stdout.  In the terminal used by VSCode when either the writing to stdout, or the reponse being emitted to stdin, it will scroll back.

Because we have an event subscriber, PSReadLine will attempt to process events when the a key read times out (every 200ms).  Before it checks for events, it checks cursor position so if the event subscriber writes to stdout, it can reposition the prompt.

Upstream issue: Microsoft/node-pty#211

**Comment by tylerl0706** [comment]
I'm going to pray to the node-pty gods (aka @Tyriar) that this gets fixed. Right now our options are:

* Don't use PSReadLine for Unix
* use some hack in PSReadLine to stop asking for Cursor position [here](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L239-L245)

Both options make me 😢

**Comment by rjmholt** [comment]
https://github.com/xtermjs/xterm.js/issues/1579 is currently tracking this. Looks like it will be fixed in VSCode-Insiders within the week.
