### ISSUE TITLE
VS Code thinks the ' in a regular expression is the start of a string

### ISSUE THREAD

**Issue by PSPally** [PowerShell/PowerShellEditorServices#731]
When I use a ' in a regular expression the editor thinks it's the start of a text string.  The code is all green like it's a comment until it finds another '.

i.e. [ValidatePattern(“^[-'a-z]*$”)]

It runs fine in PowerShell itself.

**Comment by rjmholt** [comment]
Hi @PSPally, syntax issues are handled by the https://github.com/PowerShell/EditorSyntax/ repo. Please [report the issue](https://github.com/PowerShell/EditorSyntax/issues/new) there if it persists after following all the steps in the issue template.

Will close the issue here in favour of opening one in EditorSyntax.
