### ISSUE TITLE
Consider moving to Omnisharp's LSP package

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellEditorServices#950]
Omnisharp now has:

https://github.com/OmniSharp/csharp-language-server-protocol

which gives us both a client and server library to pull in:
https://www.nuget.org/packages?q=OmniSharp.Extensions

Client for Pester tests, Server to replace a lot of PSES.Protocol.

This is a pretty large work item, but it would be awesome to share a fundamental layer of a Lanaguage Server with the C# extension.

cc @david-driscoll

**Comment by rjmholt** [comment]
So some notes on this so far, since I've been working on this for about a week now:

- The language server configuration requires a [Microsoft.Extensions.Logging.ILoggerFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.iloggerfactory?view=aspnetcore-2.2) implementation, so we'll need to change our logging over and come up with a good solution for being able to share logging between the LSP server and the other layers. [Serilog has a solution to this I think](https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerFactory.cs), but we'll need to convert over all our logging.
    - Another problem here is that it will likely break our logging format, which I don't really want to do since @rkeithhill put so much work in. But we might be able to work around some of this, or work with OmniSharp to make it more configurable.

- The LSP implementation makes heavy use of ASP-style dependency injection (using an `IServiceCollection`), which makes perfect sense. But we're not nearly set up for this, so we'll need to make a bunch of changes there for initial setup. Essentially I think the right approach here is to turn services and handlers into things that get automatically injected into each other, with a more formalised concept of layers.

- Handlers must implement implement `IJsonRpcHandler` which have a `Handle` method (returning the response type in the case of request handlers), whereas ours are event-subscribed delegates that take a context type to send responses/events and return a void `Task`. I wrote some adapters that plumb our model into the other, but it's clear to me now that it's not as simple as this because of the dependency injection and it will be the same amount of work to do it properly.
    - One consequence of this is that all the request and event types must implement `IRequest<TResponse>` to mark them for the handler library. There's no actual interface to implement but it must be done due to generic type constraints.
    - Another thing is that `IJsonRpcRequestHandler<TResponse>` doesn't have an obvious way to send a custom error response, which is an API our current implementation offers. I've asked about that in https://github.com/OmniSharp/csharp-language-server-protocol/issues/144.

- Most of our existing functionality invoked by handlers would now fit best as "Services"; AnalysisService and ExtensionSevice are examples where this is an easy (and pre-empted) move, but Workspace and PowerShellContext may require more care.

- This LSP implementation looks like it will buy us request cancellation for free.

### Current Proposal

After trying adapt our existing delegates to drop in to OmniSharp, they couple a lot to our existing not-so-cohesive LSP implementation and plumbing through the dependencies in a way that doesn't cause issues will be a big pain.

So instead I'm going to try to create a prototype with:
- All the "Service" layers implementing a service interface of some kind
- Handlers implemented as their own classes with dependencies injected

(There are more things I think I want to put here but I can't recall them at the minute. I'll update later)

**Comment by david-driscoll** [comment]
Sorry I've been kind of un-attentive as of late.  Let me know if you need any help solving issues and I'll try keep an eye on my notifications!

**Comment by rjmholt** [comment]
I believe this can now be closed 😉
